### ISSUE TITLE
引入 小程序用的wx.js  webpack报错。

### ISSUE THREAD

**Issue by callmesoul** [wendux/fly#155]
```
VM5243:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot assign to read only property 'exports' of object '#<Object>' 
 TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at webpackUniversalModuleDefinition (http://127.0.0.1:31692/appservice/app.js:4625:81)
    at Module.<anonymous> (http://127.0.0.1:31692/appservice/app.js:4632:3)
    at Module.<anonymous> (http://127.0.0.1:31692/appservice/app.js:5690:30)
    at __webpack_require__ (http://127.0.0.1:31692/appservice/runtime.js:79:30)
    at Module.<anonymous> (http://127.0.0.1:31692/appservice/app.js:6213:11)
    at __webpack_require__ (http://127.0.0.1:31692/appservice/runtime.js:79:30)
    at Module.<anonymous> (http://127.0.0.1:31692/appservice/app.js:6161:65)
    at __webpack_require__ (http://127.0.0.1:31692/appservice/runtime.js:79:30)
    at Module.<anonymous> (http://127.0.0.1:31692/appservice/app.js:6148:63)
    at __webpack_require__ (http://127.0.0.1:31692/appservice/runtime.js:79:30)
```
百度了下
```
同过谷歌查找，和论坛各种搜索:

原因如下：The code above is ok. You can mix require and export. You can‘t mix import and module.exports.

翻译过来就是说，代码没毛病，在webpack打包的时候，可以在js文件中混用require和export。但是不能混用import 以及module.exports 。

因为webpack 2中不允许混用import和module.exports ,

解决办法就是统一改成ES6的方式编写即可.
```

**Comment by callmesoul** [comment]
用npm报那个可以
